<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       https://owlpixel.com
 * @since      1.0.0
 *
 * @package    Lorem_Carousel
 * @subpackage Lorem_Carousel/admin
 */

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Lorem_Carousel
 * @subpackage Lorem_Carousel/admin
 * @author     Anowar Hossen <anrctg@gmail.com>
 */
/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
if ( plugin_dir_path( dirname( __FILE__ ) ) . 'inc/cmb2/init.php' ) {
   require_once plugin_dir_path( dirname( __FILE__ ) ) . 'inc/cmb2/init.php';
}

add_action( 'cmb2_admin_init', 'cmb2_sample_metaboxes' );
/**
 * Define the metabox and field configurations.
 */
function cmb2_sample_metaboxes() {

    /**
     * Initiate the metabox
     */
    $cmb = new_cmb2_box( array(
        'id'            => 'test_metabox',
        'title'         => __( 'Upload Carousel Images', 'cmb2' ),
        'object_types'  => array( 'lorem_carousel' ), // Post type
        'context'       => 'normal',
        'priority'      => 'high',
        'show_names'    => true, // Show field names on the left
        // 'cmb_styles' => false, // false to disable the CMB stylesheet
        // 'closed'     => true, // Keep the metabox closed by default
    ) );

    $cmb->add_field( array(
        'name' => 'Carousel Images',
        'desc' => '',
        'id'   => 'carousel_images_group',
        'type' => 'file_list',
        'preview_size' => array( 200, 200 ), // Default: array( 50, 50 )
        // 'query_args' => array( 'type' => 'image' ), // Only images attachment
        // Optional, override default text strings
        'text' => array(
            'add_upload_files_text' => 'Add Image For Carousel', // default: "Add or Upload Files"
            'remove_image_text' => 'Replacement', // default: "Remove Image"
            'file_text' => 'Replacement', // default: "File:"
            'file_download_text' => 'Replacement', // default: "Download"
            'remove_text' => 'Replacement', // default: "Remove"
        ),
    ) );


    $cmb = new_cmb2_box( array(
        'id'            => 'lc_settings',
        'title'         => __( 'Settings for this carousel', 'cmb2' ),
        'object_types'  => array( 'lorem_carousel' ), // Post type
        'context'       => 'normal',
        'priority'      => 'high',
        'show_names'    => true, // Show field names on the left
        // 'cmb_styles' => false, // false to disable the CMB stylesheet
        // 'closed'     => true, // Keep the metabox closed by default
    ) );

    $cmb->add_field( array(
        'name'             => 'Nav',
        'id'               => 'lc_loop',
        'type'             => 'radio_inline',
        'options'          => array(
            '1' => __( 'Loop Carousel', 'cmb2' ),
            '0'   => __( 'Do not loop carousel', 'cmb2' )
        ),
        'default' =>1
    ) );
    $cmb->add_field( array(
        'name'             => 'Nav',
        'id'               => 'lc_nav',
        'type'             => 'radio_inline',
        'options'          => array(
            '1' => __( 'Show Nav', 'cmb2' ),
            '0'   => __( 'Hide Nav', 'cmb2' )
        ),
        'default' =>1
    ) );
    $cmb->add_field( array(
        'name'             => 'Dots',
        'id'               => 'lc_dots',
        'type'             => 'radio_inline',
        'options'          => array(
            '1' => __( 'Show Dots', 'cmb2' ),
            '0'   => __( 'Hide Dots', 'cmb2' )
        ),
        'default' =>0,
        'desc' => 'Hide or show the dots on navigations. Default hidden',
    ) );



}



// Add Shortcode
function lorem_carousel_shortcode( $atts ) {
    global $nav,$dots,$loops,$lc_id;
    // Attributes
    $atts = shortcode_atts(
        array(
            'carousel_id' => '105',
        ),
        $atts
    );




    //$text = get_post_meta( $atts->carousel_id, 'carousel_images_group', true );
    // Get the list of files
    $files = get_post_meta( $atts['carousel_id'], 'carousel_images_group', 1 );
    $nav = get_post_meta( $atts['carousel_id'], 'lc_nav', 1 );
    $dots = get_post_meta( $atts['carousel_id'], 'lc_dots', 1 );
    $loops = get_post_meta( $atts['carousel_id'], 'lc_loop', 1 );
    $lc_id = "lorem_carousel_".$atts['carousel_id'];

    $data = "";
    $data.= '<div class="owl-carousel owl-theme" id="'.$lc_id.'">';
    // Loop through them and output an image
    foreach ( (array) $files as $attachment_id => $attachment_url ) {
        $data.= '<div class="item">';
        $data.= wp_get_attachment_image( $attachment_id, 'full' );
        $data.= '</div>';
    }
    $data.= '</div>';

    function lc_js_settings() {
        global  $nav, $dots, $loops, $lc_id;
            if ($nav == '1'){
                $showNav = 'true';
            }elseif($nav == '0'){
                $showNav = 'false';
            }
            if ($dots == '1'){
                $showDots = 'true';
            }elseif($dots == '0'){
                $showDots = 'false';
            }
            if($loops == '1'){
                $showLoop = 'true';
            }elseif($loops == '0'){
                $showLoop = 'false';
            }
        ?>
        <script type="text/javascript">
            jQuery(document).ready(function ($) {
                $("#<?php echo $lc_id; ?>").owlCarousel({
                    dots:<?php echo $showDots;  ?>,
                    loop:<?php echo $showLoop;  ?>,
                    margin:10,
					autoplay:true,
                    nav:<?php echo $showNav;  ?>,
                    items:1,
                    autoHeight:true,
                    navText: ["<strong>◀ </strong> "," <strong>▶</strong> "]
                });


            })


        </script>
        <?php
    }
    add_action( 'wp_footer', 'lc_js_settings' );


       return $data;


}
add_shortcode( 'lorem-carousel', 'lorem_carousel_shortcode' );